### ISSUE TITLE
Library Bugs : Nothing appears

### ISSUE THREAD

**Issue by Ahozuh** [Moomooo95/moomooo95-extensions#8]
Hello,

don’t know why but from theses sources I can’t put anything in the library it doesn’t appear ( it’s only working for the source Phoenix_scan)

As you can see in the files, in the collection « francais » there is 15 differents titles but only 3 appears in the library and i don’t understand why the 12 left are not there?  When i want to refresh you can see that only phoenix scan (from your sources) appears …

do you know if the problem can be solve ? 

![IMG_0543](https://github.com/Moomooo95/moomooo95-extensions/assets/159493502/b40e984c-8a6d-4dde-ab36-63b13831c58b)
![IMG_0544](https://github.com/Moomooo95/moomooo95-extensions/assets/159493502/57d67ea5-72fb-478b-b4f1-1a0966f9a2dd)

Moreover the sources : FrScan / Manga_Scantrad / Scantrad_VF aren’t working anymore..

thanks for your help !

**Comment by Moomooo95** [comment]
Hello,
Sorry for the late reply (hopefully your issue is already sorted). 
The problem is probably coming from the Paperback app.
I'm doing an overall update on the repo, though I'm not very active on it.
