### ISSUE TITLE
[ SushiScan . Net ] Cloudflare Block

### ISSUE THREAD

**Issue by F4BB** [Moomooo95/moomooo95-extensions#9]
Bonjour,

J'ai essayé d'utiliser l'extension pour le site Sushi Scan afin de profiter des titres hors ligne quand je suis dans le train. Cependant, Cloudflare me bloque immédiatement, que ce soit avec un iPhone en 4G/Wi-Fi ou un iPad dans les mêmes conditions.
J'ai également essayé avec un VPN, mais j'ai obtenu le même résultat.

Je ne sais pas s'il est possible de corriger cela directement sur la source. J'ai testé divers logiciels comme Aidoku et d'autres sources où Sushi Scan fonctionne sans problème. Mais, comme vous pouvez l'imaginer, il est difficile de changer ses habitudes. Si vous aviez un tout petit peu de temps pour regarder ce problème, cela m'aiderait beaucoup. J'aimerais pouvoir contribuer et résoudre ce souci, mais cela dépasse largement mes capacités.

Merci d'avance.

![IMG_2465](https://github.com/user-attachments/assets/a2457005-9873-4ab3-90a3-39daa5ad0ea8)

**Comment by Moomooo95** [comment]
Bonjour, 
Je viens de mettre à jour la source.
Il s'agissait d'un problème d'user-agent. Celui utilisé par Paperback était bloqué, j'en ai donc défini un autre.

**Comment by F4BB** [comment]
Génial ! L’accès est rétabli. Je peux à nouveau consulter et lire. 


(pour informations le téléchargement lui ne fonctionne plus avec la dernière version de Paperback je surveille une update de l’app je me permettrai de créer une nouvelle issues) 

en tout cas merci encore ça me dépanne fort.
